### ISSUE TITLE
Rebuild the whole lot

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/trumps.spacing#8] opened 2015-03-03 13:14 UTC
1) I would like to generate all of this in a more sane manner, as we have done with the widths.

2) My hipster naming (e.g. `.p--`) is going to look absolutely ridiculous when it comes in line with the widths’ naming convention. We’ll end up with classes like `.u--m---palm`, which is:

* `u-`: utility namespace.
* `-m`: negative margin.
* `--`: tiny.
* `-palm`: breakpoint.

This is just plain weird and confusing.

I propose we move to classes like `.u-p-tiny-palm`,  `.u-mb-large-desk`.

Opinions?

**Comment by Crawleyprint** [comment] 2015-03-03 13:26
Makes sense, but I'll miss 'hipster naming' :D

**Comment by nenadjelovac** [comment] 2015-03-03 13:27
This is going to hurt :) A lot of people (including myself) really dig current naming. 

I don't have an idea ATM, but I understand where you're coming from.

**Comment by csshugs** [comment] 2015-03-03 13:31
Disregarding that I'm already using `.mb-`, `.pl++` etc. rather frequently in my projects (and loving it for its shortness) I think something like `.u-p-tiny-palm` is likely better than `.u--m---palm`. In the end it is just a mind change and the idea behind it is worth the bit more typing I think.

**Comment by nenadjelovac** [comment] 2015-03-03 13:35
>  In the end it is just a mind change and the idea behind it is worth the bit more typing I think.

I totally agree.

Plus it'll be 

> I propose we move to classes like .u-p-tiny-palm, .u-mb-large-desk.

So what would be naming convention for negative? `.u-m-large-negative-lg` or `.u-m-negative-large-lg` or, `.u-negative-m-large-lg`?

**Comment by csswizardry** [comment] 2015-03-03 13:35
You can always version-lock the hipster naming if you want to keep it :)

**Comment by florianbouvot** [comment] 2015-03-03 13:45
I'll miss 'hipster naming' too. People really use negative margin ?

Whitout négative marin we can keep the old version:

- `.u-mb++`
- `.u-palm-mb++`
etc.

**Comment by nenadjelovac** [comment] 2015-03-03 13:46
@florianbouvot have used it on few projects.

Your examples are missing breakpoint versions.

```
.u-mb++-lg
.u-palm-mb++-xs
```

That looks really weird to me :-/

**Comment by nenadjelovac** [comment] 2015-03-03 13:47
@csswizardry 
> Good point… Hmmmmmmmm. One to think about, certainly!

My candidate is `.u-m-negative-large-lg`

**Comment by Crawleyprint** [comment] 2015-03-03 13:53
@nenadjelovac I like @florianbouvot's version better :)

**Comment by nenadjelovac** [comment] 2015-03-03 13:55
@florianbouvot my bad, I just saw that you did it right.

**Comment by florianbouvot** [comment] 2015-03-03 13:55
@nenadjelovac sorry but in my examples I put responsive versions

**Comment by Crawleyprint** [comment] 2015-03-03 13:56
As for negative margins (yes, I'm using them), we might do something like:

- `.u-nmb++` 
- `.u-palm-nmb--`

**Comment by florianbouvot** [comment] 2015-03-03 13:59
@nenadjelovac have used it in one or two project in one year (negative margin).

@Crawleyprint I like it ;)

@csswizardry why did you reverse responsive and utility name (`.palm-1/2` to `.u-1/2-palm`)?

**Comment by nenadjelovac** [comment] 2015-03-03 14:01
@florianbouvot 

> why did you reverse responsive and utility name (.palm-1/2 to .u-1/2-palm)?

My guess: `.utility-classname-modifier-breakpoint`

**Comment by florianbouvot** [comment] 2015-03-03 20:40
> My guess: .utility-classname-modifier-breakpoint

I understand, but I want to know what benefit it brings?

**Comment by florianbouvot** [comment] 2015-03-05 13:29
Side question : someone know why @necolas remove this utility from  SUITCSS?

**Comment by csswizardry** [comment] 2015-03-13 14:06
Just had a thought about naming these.

How about instead of the `-palm`, `-lap`, etc. suffixes, we use `@palm`, `@lap`?

**Examples:**

We could keep hipsterness (although I’m still not sure it’s wise):

```
.u-mb++@palm {}
```

Or we can have text:

```
.u-mb-huge@lap {}
```

The `@breakpoint` convention could be used across all of inuitcss, and makes things pretty readable, e.g.:

```
<div class="o-layout__item  u-1/1  u-1/2@md  u-1/4@lg">
```

Thoughts?

**Comment by csswizardry** [comment] 2015-03-13 14:12
**UPDATE:** [Demo](http://sassmeister.com/gist/07a4fe87a7037b022b42)

**Comment by csshugs** [comment] 2015-03-13 14:14
I think this is a pretty great idea (without having tested it thoroughly). It looks very obvious (in the markup) and as you said: it's readable.

But what about negative margins? Any naming suggestion for that?

**Comment by csswizardry** [comment] 2015-03-13 14:21
I don’t know if to drop -ve margins or not. I think we could do to make this file a lot smaller! People can polyfill -ve margins locally very easily if they need to.

Ahh, I dunno :shrug:

**Comment by csshugs** [comment] 2015-03-13 14:25
I just thought the same. I actually very rarely use negative margins, so yeah. Maybe we could drop them.

(In fact negative marings are very ugly, aren't they?)

**Comment by csswizardry** [comment] 2015-03-13 14:26
They’re useful and valid (I never understood why people hated on them so much) but yeah, I dunno if they need packaging up 100% of the time :)

**Comment by nenadjelovac** [comment] 2015-03-13 14:26
@csswizardry  I totally agree with @csshugs , this is very obvious and readable. 

My candidate would be `.u-m-negative-large@lg` or `.u-negative-margin-large@lg`. But feels so weird :-/

>I don’t know if to drop -ve margins or not. I think we could do to make this file a lot smaller! People can polyfill -ve margins locally very easily if they need to.

Don't drop it :)

**Comment by csswizardry** [comment] 2015-03-13 14:30
We want to name things in a drilldown approach, so regardless of the actual wording, it would have to follow:

```
.<namespace><category>[<direction>]<size>[<breakpoint>] {}
```

E.g.:

```
.u-m-negative-large@sm {}

.u-pb-small@sm {}
```

Wow, that’s ugly haha!

**Comment by nenadjelovac** [comment] 2015-03-13 14:35
Yes it is ugly. But it works. Also, a lot of people say BEM is ugly, but it also works wonders :P

**Comment by csshugs** [comment] 2015-03-13 14:37
> Also, a lot of people say BEM is ugly, but it also works wonders

Exactly @nenadjelovac!

That looks logical to me, too. But what **does** look a bit ugly is the word "negative":

> Is there an abbreviation for negative in English (something like rev for .layout, .media and .flag)? neg?

What about this? Is there an abbreviation for "negative"? (sorry, me no english man)

**Comment by csswizardry** [comment] 2015-03-13 14:40
> Is there an abbreviation for "negative"?

Yeah, it’s the minus symbol >.<

**Comment by nenadjelovac** [comment] 2015-03-13 14:43
> What about this? Is there an abbreviation for "negative"? (sorry, me no english man)

Negative actually seems like the best option for us non-native english speakers (I just googled for "negative" synonyms).

**Comment by csswizardry** [comment] 2015-03-13 14:44
Also, it is only margins that can take negative values, so it will only happen in one place.

However, I’d like us all to keep this in mind as well: http://csswizardry.com/2015/03/can-css-be-too-modular/

I want to make sure we don’t (inadvertently) promote the overuse of utilities and helpers…

**Comment by csshugs** [comment] 2015-03-13 14:45
> (I just googled for "negative" synonyms)

Haha, I did myself. Can't find any other words that fit here.

**Comment by csshugs** [comment] 2015-03-13 14:53
> I want to make sure we don’t (inadvertently) promote the overuse of utilities and helpers…

I agree, although I consider trumps.spacings as a welcome exception. They're so, so useful. But as I stated above, that doesn't necessary apply to negative margins. So dropping them is an opportunity. 
Don't shure about that neither.

**Comment by Crawleyprint** [comment] 2015-03-13 15:07
I have used negative margins before, but it's not something I can't live without. However, if you have `.<namespace><category>[<direction>][<size>][<breakpoint>] {}` what stops us to declare 'negative left' as a direction? In that case, we'll abbreviate it as `nl`, eg. `.m-nl-huge@palm`. 

I can see hipster naming is going away - @csswizardry you got to stop that, I just got used to it :) Joke aside, I really like  `@breakpoint` idea, makes responsive classes more visible.

**Comment by mhauken** [comment] 2015-03-16 17:13
A bit late to the party, but here is a few thoughts from me:
* `@palm` etc is a great and very logical idea! Especially on widths: can't wait to write out `1/2@desk` etc.
* `-small`, `-large` is more in line with rest of inuit like `.box` and `.btn`. 
* I find it a bit weird that `small` etc don't have two dashes like modifiers do. `.u-pb--small@sm` seems more in line with BEM-naming even though it's not strictly a modifier. Especially when you think of `.box--small`, `.btn-small` it's a bit weird that these utilities only have one dash and the rest two.
* I always thought of negative margins as minusmargin. Could that be of help? `.u-mm` or `.u-mn` for example?

**Comment by jonhurrell** [comment] 2015-03-19 15:36
@jameshoward @jamesmd) and myself are go for the @ suffix. A way to denote a negative value could be parentheses (used in accounting). E.g.
`.u-mb(--)@palm`

**Comment by Crawleyprint** [comment] 2015-03-19 18:12
I think parentheses would be too much...

**Comment by csshugs** [comment] 2015-06-18 13:10
After thinking about it thoroughly and using it in a project at the moment, I would go for:
```
.u-mb-negative-large-palm {}
```
This would result in loosing the 'hipster naming'. Yes, hipster naming is cool, the classes are short, but the classes are far more declarative in what they actually do (Readablilty in the markup). Ever tried to explain these `++`/`--` naming conventions to an inuit-newbie? Not to mention the responsive-negative variations as it is at the moment (`u-palm--mb--`)? It's just ridiculously confusing for them (actually quoting an inuit newbie here) and just not obvious without knowing the convention.

Negative margins are used very rarely, so we'd not often have such long classes as above but rather classes like:
```
.u-pt {}
.u-mb-small {}
.u-mb-none-palm {}
```
Don't know if to keep `mb0` naming here or changing it as above to something like `mb-none` to keep it more consequent and understandable for devs not that familiar with inuitcss (declarative classes).

---
The next step would be integrating the `@` symbol for responsive modifiers as [suggested by Harry](https://github.com/inuitcss/trumps.spacing/issues/8#issuecomment-78985905) like:
```
.u-mb-negative-large@palm {}
```

and transfer this to the widths as well. This really improves the readability in the markup in my opinion.

**Comment by csshugs** [comment] 2015-06-22 09:47
@csswizardry @nenadjelovac @anselmh 
Is it worth a Pull Request?

**Comment by nenadjelovac** [comment] 2015-06-23 16:38
@csshugs absolutely IMO ;)

**Comment by csshugs** [comment] 2015-06-24 10:51
> 1) I would like to generate all of this in a more sane manner, as we have done with the widths.

Considering this first point of @csswizardry, what about something like this:
http://sassmeister.com/gist/ecb9756749eaa0a18eb8 ?
I'm really not sure, if we win that much with something like this. Maybe someone more familiar with Sass can thin it out a bit?

**Comment by csshugs** [comment] 2016-01-05 09:14
> 1) I would like to generate all of this in a more sane manner, as we have done with the widths.

I'm not sure about that anymore. 

The difference to the widths is the dynamic. 
With the widths you could not have dynamic number of columns (12, 24, 36 etc.) without generating it. Before that was changed, there was no alternative to have a 12-columns-grid. 
Now we can have whatever grid we want, which is fantastic. So the complexity which was introduced via Sass in this case was a huge gain in the outcome. Simplicity was sacrificed for a real improvement in the generated CSS.

Whereas introducing some king of generation for *this* module would have no impact in the way we interact with a project. Our architectural approach related to spacings would not change. The generated CSS would be the same.
All it would do is minimizing the length of the source file. But we would be trading that off with a huge gain in complexity. I'm afraid that could be leading to a high entry-barrier and it's harder to debug.

**Comment by BenjaminRCooper** [comment] 2016-07-01 13:25
Should have read this thread before creating #13. Sorry guys, great work.

**Comment by csshugs** [comment] 2016-08-05 13:07
@inuitcss/core I think we will not address this in this version of inuitcss. Since this is not a bug, can we close this?

**Closed** 2016-08-30 08:13 UTC
Labels: enhancement
